import { EventTypes } from '../../../shared/events';

export const PaymentEventTypes = {
  PAYMENT_CREATED: EventTypes.PAYMENT_CREATED,
  PAYMENT_APPROVED: EventTypes.PAYMENT_APPROVED,
  PAYMENT_PENDING: EventTypes.PAYMENT_PENDING,
  PAYMENT_REJECTED: EventTypes.PAYMENT_REJECTED,
  PAYMENT_CANCELLED: EventTypes.PAYMENT_CANCELLED,
  PAYMENT_REFUNDED: EventTypes.PAYMENT_REFUNDED,
  PAYMENT_CHARGEBACK: EventTypes.PAYMENT_CHARGEBACK,
  PAYMENT_WEBHOOK_RECEIVED: EventTypes.PAYMENT_WEBHOOK_RECEIVED,
  PAYMENT_RECONCILIATION_NEEDED: EventTypes.PAYMENT_RECONCILIATION_NEEDED,
} as const;
