export enum InventoryEventName {
  PRODUCT_CREATED = 'product.created',
  PRODUCT_UPDATED = 'product.updated',
  PRODUCT_DELETED = 'product.deleted',
  STOCK_ADJUSTED = 'inventory.updated',
  LOW_STOCK_ALERT = 'inventory.low.stock',
  STOCKOUT = 'inventory.stockout',
  SUPPLIER_CREATED = 'supplier.created',
  PURCHASE_ORDER_RECEIVED = 'purchase.order.received',
  PURCHASE_SUGGESTION_GENERATED = 'purchase.suggestion.generated',
  KPI_UPDATED = 'inventory.kpi.updated',
  DASHBOARD_UPDATED = 'inventory.dashboard.updated',
  SALE_ITEM_ADDED = 'sale.item.added',
  SALE_CONFIRMED = 'sale.confirmed',
  SALE_CANCELLED = 'sale.cancelled',
  RENTAL_STARTED = 'rental.started',
  RENTAL_FINISHED = 'rental.finished',
}
